In [48]:
import copy
import numpy as np

In [49]:
# Multiple Variable Linear Regression for House Price Prediction

In [50]:
# Training set
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

In [51]:
# Visualise your data
print(f"X Shape: {X_train.shape}, X Type:{type(X_train)})")
print(f"y shape: {y_train.shape}, y Type:{type(y_train)})")

X Shape: (3, 4), X Type:<class 'numpy.ndarray'>)
y shape: (3,), y Type:<class 'numpy.ndarray'>)


In [52]:
# Parameter vectors
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>


In [53]:
# Single prediction
def single_prediction(x, w, b):
    """
    Predict a house price using untuned parameters with 
        a single training example.

    Args:
        x (ndarray): Shape (n,) example with multiple features
        w (ndarray): Shape (n,) model parameters
        b (scalar):  model parameter

    Returns:
        p (scalar):  house price prediction
    """
    m = x.shape[0]
    p = 0.0
    for i in range(m):
        p_i = w[i] * x[i]
        p = p + p_i
    p = p + b
    return p

In [54]:
price = single_prediction(X_train[0], w_init, b_init)
print(price)

459.9999976194083


In [55]:
# get a row from our training data
x_vec = X_train[0,:]
print(f"x_vec shape {x_vec.shape}, x_vec value: {x_vec}")

x_vec shape (4,), x_vec value: [2104    5    1   45]


In [56]:
# Single prediction, vectorised
def single_prediction_vectorised(x, w, b):
    """
    Predict a house price using untuned parameters with 
        a single training example, now using the NumPy dot() method.

    Args:
        x (ndarray): Shape (n,) example with multiple features
        w (ndarray): Shape (n,) model parameters
        b (scalar) : model parameter

    Returns:
        p (scalar): prediction
    """
    f_wb = np.dot(x, w) + b
    return f_wb

In [57]:
house_price = single_prediction_vectorised(X_train[0], w_init, b_init)
print(house_price)

459.9999976194083


In [58]:
# Compute cost for multiple variable linear regression
def cost(X, y, w, b):
    """
    Compute the cost of the multiple linear regression model function.

    Args: 
        X - matrix of the training data
        y - target values (vector)
        w - weights (vector)
        b - parameters (vector)

    Returns:
        Cost for the multiple linear regression model function.
    """
    m = X.shape[0]
    cost = 0.0
    for i in range(m):
        f_wb_i = np.dot(X[i],w) + b  # For every training example...
        cost = cost + (f_wb_i - y[i]) ** 2
    cost = cost / (2 * m)
    return cost

In [59]:
cost = cost(X_train, y_train, w_init, b_init)
print(cost)

1.5578904428966628e-12


In [60]:
print(X_train)
print(X_train.shape)
print(X_train[1])  # Looping over training examples using this

[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
(3, 4)
[1416    3    2   40]


In [61]:
# Compute gradients
def grad(X, y, w, b):
    """
    Args:
        X - matrix of the training set
        y - vector of target values
        w - vector of parameters
        b - vector of parameters
    """
    m, n = X.shape
    dJ_dw = np.zeros(n)
    dJ_db = 0.0
    # Gradients computed for each feature, for each training example
    for i in range(m):
        f_wb_i = np.dot(X[i],w) + b  # Compute model based on example
        dJ_db = dJ_db + (f_wb_i - y[i])
        for j in range(n):
            dJ_dw[j] = dJ_dw[j] + (f_wb_i - y[i]) * X[i,j]
    dJ_dw = dJ_dw / m
    dJ_db = dJ_db / m
    return dJ_dw, dJ_db

In [62]:
dJ_dw, dJ_db = grad(X_train, y_train, w_init, b_init)
print(f"dJ_dw: {dJ_dw}")
print(f"dJ_db: {dJ_db}")

dJ_dw: [-2.72623577e-03 -6.27197263e-06 -2.21745578e-06 -6.92403391e-05]
dJ_db: -1.6739251501955248e-06


In [65]:
# Compute gradient descent
def gradient_descent(X, y, w_in, b_in, cost, grad, alpha, iterations):
    """
    """
    J_history = []
    w = copy.deepcopy(w_in)
    b = b_in

    for i in range(iterations):
        dJ_dw, dJ_db = grad(X, y, w, b)
        w = w - alpha * dJ_dw
        b = b - alpha * dJ_db
